metrics: true

# Current scoreboard file name
scoreboard-title: "&d&kiii &r&b&lScoreboard &d&kiii" #You can use minecraft's and essentials' color format (§0 = &0 = black)
scoreboard-min-size: 20 # Max size is 32

scoreboard-lines:
  - "&6Welcome, {displayname}"
  - ""
  - "&1Players Online »"
  - "&b{online}/{maxplayers}"
  - ""
  - "&1Money »"
  - "&a{money}"
  - ""
  - "&eChechu's Custom Scoreboard"